inherit_from: .rubocop_todo.yml
plugins:
  - rubocop-performance
  - rubocop-rails
  - rubocop-minitest
  - rubocop-capybara
  - rubocop-factory_bot

AllCops:
  Exclude:
    - config/initializers/forbidden_yaml.rb
    - app/helpers/dynamic_errors_helper.rb
    - !ruby/regexp /(vendor|bundle|bin|db/(migrate/|schema\.rb)|tmp|server)($|\/.*)/
  DisplayCopNames: true
  DisplayStyleGuide: true
  ParserEngine: parser_prism
  TargetRubyVersion: 3.4
  NewCops: enable

Rails/SkipsModelValidations:
  Enabled: false

Rails/LexicallyScopedActionFilter:
  Enabled: false

Rails/RefuteMethods:
  Enabled: false

Rails/HelperInstanceVariable:
  Enabled: false

Rails/FilePath:
  Enabled: false

Rails/UnknownEnv:
  Environments:
    - production
    - development
    - staging
    - test

Rails/UniqueValidationWithoutIndex:
  Enabled: false

Rails/ActionControllerTestCase:
  Enabled: false # Causes every integration test to fail

Rails/Output:
  Exclude:
    - app/views/**/*_view.rb
    - app/views/**/*_component.rb

# Disable block forwarding style enforcement - let context determine choice
Naming/BlockForwarding:
  Enabled: false

Style/ArgumentsForwarding:
  Enabled: false

Layout/ArgumentAlignment:
  Enabled: false

Metrics/AbcSize:
  Max: 42 # TODO: Lower to 15
  Exclude:
    - test/functional/api/v1/owners_controller_test.rb
    - db/**/*.rb

Metrics/BlockLength:
  Exclude:
    - test/**/*.rb
    - lib/tasks/**/*.rake
    - lib/github_oauthable.rb
    - app/models/concerns/**/*.rb
    - config/routes.rb
    - config/environments/development.rb
    - db/**/*.rb

Metrics/ClassLength:
  Max: 357 # TODO: Lower to 100
  Exclude:
    - test/**/*
    - db/**/*.rb

Metrics/CyclomaticComplexity:
  Max: 9 # TODO: Lower to 6

Layout/LineLength:
  Max: 150

Metrics/MethodLength:
  Max: 30 # TODO: Lower to 10
  Exclude:
    - db/**/*.rb

Metrics/ModuleLength:
  Exclude:
    - lib/patterns.rb
    - app/models/concerns/rubygem_searchable.rb
    - app/helpers/rubygems_helper.rb

Metrics/PerceivedComplexity:
  Max: 10 # TODO: Lower to 7

Performance/RedundantMerge:
  Enabled: false

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/HashAlignment:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Style/AndOr:
  Exclude:
    - app/controllers/internal/ping_controller.rb

Naming/AccessorMethodName:
  Exclude:
    - app/controllers/application_controller.rb

Rails/SafeNavigation:
  ConvertTry: true

Style/Documentation:
  Enabled: false

Style/FetchEnvVar:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
  Exclude:
    - config/**/*

Style/FrozenStringLiteralComment:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/FormatStringToken:
  Enabled: false

Style/HashAsLastArrayItem:
  EnforcedStyle: no_braces

Style/HashSyntax:
  EnforcedShorthandSyntax: either

Minitest/MultipleAssertions:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
  Exclude:
    - lib/gemcutter/middleware/hostess.rb
    - lib/gemcutter/middleware/redirector.rb

Capybara/ClickLinkOrButtonStyle:
  Enabled: false

Rails/ThreeStateBooleanColumn:
  Enabled: false

Lint/UselessConstantScoping:
  Enabled: false
